DOMAIN = "sma_bt_native"

CONF_BT_ADDRESS = "bt_address"
CONF_PASSWORD = "password"
CONF_AC_INTERVAL = "ac_interval"
CONF_ENERGY_TODAY_INTERVAL = "energy_today_interval"
CONF_ENERGY_TOTAL_INTERVAL = "energy_total_interval"
CONF_TEMPERATURE_INTERVAL = "temperature_interval"
CONF_BLUETOOTH_SIGNAL_INTERVAL = "bluetooth_signal_interval"
CONF_MPPT_INTERVAL = "mppt_interval"

DEFAULT_AC_INTERVAL = 30
DEFAULT_ENERGY_TODAY_INTERVAL = 180
DEFAULT_ENERGY_TOTAL_INTERVAL = 180
DEFAULT_TEMPERATURE_INTERVAL = 60
DEFAULT_BLUETOOTH_SIGNAL_INTERVAL = 180
DEFAULT_MPPT_INTERVAL = 30

SENSOR_AC_POWER = "ac_power"
SENSOR_ENERGY_TODAY = "energy_today"
SENSOR_ENERGY_TOTAL = "energy_total"
SENSOR_TEMPERATURE = "inverter_temperature"
SENSOR_OPERATION_TIME = "operation_time"
SENSOR_FEED_IN_TIME = "feed_in_time"
SENSOR_BLUETOOTH_SIGNAL = "bluetooth_signal"
SENSOR_MPPT1_POWER = "mppt1_power"
SENSOR_MPPT2_POWER = "mppt2_power"
SENSOR_DC_TOTAL_POWER = "dc_total_power"
SENSOR_STATUS = "status"
SENSOR_EFFICIENCY = "efficiency"
BINARY_SENSOR_CONNECTED = "connected"
